version: "0.1"

services:
  # db:
  #   build: .
  #   container_name: database
  #   restart: always
  #   ports:
  #     - 3307:3306
  #   environment:
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
  #     TZ: Asia/Seoul
  #   command:
  #     - --character-set-server=utf8mb4
  #     - --collation-server=utf8mb4_unicode_ci

  # backend:
  #   build: ../nursing-home-server/server
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
  #     SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
  #     SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
  #     KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
  #     KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
  #     NAVER_CLIENT_ID: ${NAVER_CLIENT_ID}
  #     NAVER_CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
  #     JWT_SECRET: ${JWT_SECRET}
  #     FRONTEND_URL: ${FRONTEND_URL}
  #   depends_on:
  #     - db

  frontend:
    build: ../nursing-home
    container_name: frontend
    restart: always
    ports:
      - 80:3000
